application: doctorbronowski
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /bootstrap
  static_dir: bootstrap

- url: /css
  static_dir: css

- url: /img
  static_dir: img

- url: /js
  static_dir: js

- url: .*
  script: doctorbronowski.app

libraries:
- name: jinja2
  version: latest